export const QUERY_KEYS = {
  GET_ALL_BREEDS: "GET_ALL_BREEDS",
  GET_IMAGES_BY_BREED_NAME: "GET_IMAGES_BY_BREED_NAME",
  GET_IMAGES_BY_SUB_BREED_NAME: "GET_IMAGES_BY_SUB_BREED_NAME",
  GET_IMAGE_BY_BREED_NAME: "GET_IMAGE_BY_BREED_NAME",
};
